version: 2.1
jobs:
  Development:
    docker:
      - image: google/cloud-sdk
    environment:
      - PROJECT_NAME: "Infraestructura"
      - GOOGLE_COMPUTE_ZONE: "us-central1-a"
      - VM_NAME: "mv-nfsdesarrollo"
    steps:
      - checkout
      - run:
          name: Setup Google Cloud SDK
          comand:
            apt-get install -cq -y gettext
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file-${HOME}/gcloud-service-key.json
            apt-get install -y node.js
            node -v
            apt-get install -y npn
            npn -v 
            npn -g install acorn
            acorn --silent script.js
            gcloud --quiet beta compute ssh --zone ${GOOGLE_COMPUTE_ZONE} ${VM_NAME} --project $(GOOGLE_PROJECT_ID) --ssh-flag="-t" --command="cd /var/www/web/pagina && git pull origin master;pwd"
  Production:
    docker:
      - image: google/cloud-sdk
    environment:
      - PROJECT_NAME: "Infraestructura"
      - GOOGLE_COMPUTE_ZONE: "us-central1-a"
      - VM_NAME: "nfs2"
    steps:
      - checkout
      - run:
          name: Setup Google Cloud SDK
          comand:
            apt-get install -cq -y gettext
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file-${HOME}/gcloud-service-key.json
            gcloud --quiet beta compute ssh --zone ${GOOGLE_COMPUTE_ZONE} ${VM_NAME} --project $(GOOGLE_PROJECT_ID) --ssh-flag="-t" --command="cd /var/www/web/pagina && git pull origin master;pwd"

workflows:
  version: 2.1
  build:
    jobs:
      - Development:
          filters:
            branches:
              only: master
      - Manual-Approval:
          type: Approval
          requires:
            - Development
      - Production:
          requires:
            - Manual-Approval
          filters:
            branches:
              only: master



