version: 2.1
jobs:
  Test:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          command: |
            apt-get install -qq -y gettext
            apt-get install -y nodejs
            node -v
            apt-get install -y npm
            npm -v
            npm -g install acorn
            acorn --silent server.js                                                                             
  Development:
    docker:
      - image: google/cloud-sdk
    environment:
      - PROJECT_NAME: "Infraestructura"
      - GOOGLE_COMPUTE_ZONE: "us-central1-a"
      - VM_NAME: "mv-nfsdesarrollo"
      
    steps:
      - checkout
      - run:
          name: "Setup Google Cloud SDK"
          command: |
            apt-get update -y
            apt-get install -y apt-utils
            apt-get install -qq -y gettext
            mkdir prueba
            echo $GCLOUD_SERVICE_KEY > ./prueba/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=./prueba/gcloud-service-key.json
            echo $KEY​​​​​​PU > ./prueba/key.pub
            echo $KEY​​​​​​PRI > ./prueba/key
            ssh -i ./prueba/key -o "StrictHostKeyChecking no" 782423016750-compute@35.224.124.45 "cd /mnt/nfs_share && sudo rm -r practica; git clone https://github.com/sebastianlesi/practica.git && sudo chmod 755 practica && ls"
            ssh -i ./prueba/key -o "StrictHostKeyChecking no" 782423016750-compute@10.128.0.32 "sudo docker restart f28294247010"
  Production:
    docker:
      - image: google/cloud-sdk
    environment:
      - PROJECT_NAME: "Infraestructura"
      - GOOGLE_COMPUTE_ZONE: "us-central1-a"
      - VM_NAME: "nfs2"

    steps:
      - checkout
      - run:
          name: "Setup Google Cloud SDK"
          command: |
            apt-get update -y
            apt-get install -y apt-utils
            apt-get install -qq -y gettext
            mkdir prueba
            echo $GCLOUD_SERVICE_KEY > ./prueba/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=./prueba/gcloud-service-key.json
            echo $KEY​​​​​​PU > ./prueba/key.pub
            echo $KEY​​​​​​PRI > ./prueba/key
            ssh -i ./prueba/key -o "StrictHostKeyChecking no" 782423016750-compute@34.123.99.41 "cd /mnt/nfs_share && sudo rm -r practica; git clone https://github.com/sebastianlesi/practica.git && sudo chmod 755 practica && ls"
            ssh -i ./prueba/key -o "StrictHostKeyChecking no" 782423016750-compute@104.198.211.61 "sudo docker restart 44e9563851d7"
            ssh -i ./prueba/key -o "StrictHostKeyChecking no" 782423016750-compute@34.121.240.181 "sudo docker restart d92986134433"

workflows:
  version: 2.1
  build:
    jobs:
      - Test:
        filters:
          branches:
            only: 
              - master
      - Manual-Approval:
          type: approval
          requires:
            - Test
      - Development:
          requires:
            - Manual-Approval
      - Production:
          requires:
            - Development



