version: 2.1
jobs:
  Test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          node -v
          apt-get install -y npm
          npm -v
          npm -g install acorn
          acorn --silent index.js
  Development:
    docker:
      - image: google/cloud-sdk
    environment:
      - PROJECT_NAME: "Infraestructura"
      - GOOGLE_COMPUTE_ZONE: "us-central1-a"
      - VM_NAME: "mv-nfsdesarrollo"
      
    steps:
      - checkout
      - run:
          name: "Setup Google Cloud SDK"
          command: |
            apt-get update -y
            apt-get install -y apt-utils
            apt-get install -qq -y gettext
            pwd
            mkdir prueba
            echo $GCLOUD_SERVICE_KEY > ./prueba/gcloud-service-key.json
            cat ./prueba/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=./prueba/gcloud-service-key.json
            echo $KEY​​​​​​PU > ./prueba/key.pub
            echo $KEY​​​​​​PRI > ./prueba/key
            pwd
            cat ./prueba/key.pub
            cat ./prueba/key
            ssh -i ./prueba/key -o "StrictHostKeyChecking no" 782423016750-compute@35.238.229.71 cd /mnt/nfs_share | it pull origin master
  Production:
    docker:
      - image: google/cloud-sdk
    environment:
      - PROJECT_NAME: "Infraestructura"
      - GOOGLE_COMPUTE_ZONE: "us-central1-a"
      - VM_NAME: "nfs2"

    steps:
      - checkout
      - run:
          name: "Setup Google Cloud SDK"
          command: |
            apt-get install -qq -y gettext
            pwd
            mkdir prueba
            echo $GCLOUD_SERVICE_KEY > ./prueba/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=./prueba/gcloud-service-key.json
            gcloud --quiet beta compute ssh --zone ${GOOGLE_COMPUTE_ZONE} ${VM_NAME} --project ${GOOGLE_PROJECT_ID} --ssh-flag="-t" --command="cd /mnt/nfs_share/html/html && git pull origin master;pwd" | true

workflows:
  version: 2.1
  build:
    jobs:
      - Test:
        filters:
          branches:
            only: 
              - master
      - Manual-Approval:
          type: approval
          requires:
            - Test
      - Development:
        filters:
          branches:
            only: 
              - master
      - Manual-Approval2:
          type: approval
          requires:
            - Development
      - Production:
          requires:
            - Manual-Approval2
          filters:
            branches:
              only: 
                - master



