version: 2.1
jobs:
  Development:
    docker:
      - image: google/cloud-sdk
    environment:
      - PROJECT_NAME: "Infraestructura"
      - GOOGLE_COMPUTE_ZONE: "us-central1-a"
      - VM_NAME: "mv-nfsdesarrollo"
      - GOOGLE_PROJECT_ID: "Infraestructura-287821"
    steps:
      - checkout
      - run:
          name: Setup Google Cloud SDK
          command:
            apt-get install -qq -y gettext
            echo $GCLOUD_SERVICE_KEY > ${HOME}/infraestructura-287821-f88010531f40.json
            gcloud auth activate-service-account --key-file=${HOME}/infraestructura-287821-f88010531f40.json
            apt-get install -y npm
            npm -v 
            npm install -g html-inspector
            htmlinspector /index.html
            gcloud --quiet beta compute ssh --zone ${GOOGLE_COMPUTE_ZONE} ${VM_NAME} --project $(GOOGLE_PROJECT_ID) --ssh-flag="-t" --command="cd /mnt/nfs_share && git pull origin master;pwd"
  Production:
    docker:
      - image: google/cloud-sdk
    environment:
      - PROJECT_NAME: "Infraestructura"
      - GOOGLE_COMPUTE_ZONE: "us-central1-a"
      - VM_NAME: "nfs2"
      - GOOGLE_PROJECT_ID: "Infraestructura-287821"
    steps:
      - checkout
      - run:
          name: Setup Google Cloud SDK
          command:
            apt-get install -qq -y gettext
            echo $GCLOUD_SERVICE_KEY > ${HOME}/infraestructura-287821-f88010531f40.json
            gcloud auth activate-service-account --key-file=${HOME}/infraestructura-287821-f88010531f40.json
            gcloud --quiet beta compute ssh --zone ${GOOGLE_COMPUTE_ZONE} ${VM_NAME} --project $(GOOGLE_PROJECT_ID) --ssh-flag="-t" --command="cd /mnt/nfs_share/html/html && git pull origin master;pwd"

workflows:
  version: 2.1
  build:
    jobs:
      - Development:
          filters:
            branches:
              only: master
      - Manual-Approval:
          type: approval
          requires:
            - Development
      - Production:
          requires:
            - Manual-Approval
          filters:
            branches:
              only: master



